### Importing Library

In [1]:
import numpy as np

### Hebbs Rule

In [2]:
# Define the input vectors
xl = np.array([1, 0, 1])
x2 = np.array([0, 1, 0])

# Initialize the weight matrix
w = np.zeros((3, 3))

# Apply Hebb 's rule to update the weight matrix
w += np.outer(xl, xl)
w += np.outer(x2, x2)

print("Weight matrix after applying Hebb's rule: ")
print(w)

Weight matrix after applying Hebb's rule: 
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


### Delta Rule / Widrow-Hoff Rule

In [3]:
# Define the input vector and desired output
x = np.array([1, 0, 1])
d = 1

# Initialize the weight vector and leanring rate
w = np.zeros(3)
eta = 0.1

# Repeat the training process until convergence
for i in range(100):
    # Compute the output
    y = np.dot(w, x)
    
    # Comput ethe erro between the network's and the desired output
    e = d - y
    
    # Update the weight vector using Delta Rule
    w += eta * e * x
    
    # Print the error and the weight vector
    print("Iteration: ", i + 1)
    print("Error: ", e)
    print("Weight Vector:", w, "\n")

Iteration:  1
Error:  1.0
Weight Vector: [0.1 0.  0.1] 

Iteration:  2
Error:  0.8
Weight Vector: [0.18 0.   0.18] 

Iteration:  3
Error:  0.6399999999999999
Weight Vector: [0.244 0.    0.244] 

Iteration:  4
Error:  0.512
Weight Vector: [0.2952 0.     0.2952] 

Iteration:  5
Error:  0.40959999999999996
Weight Vector: [0.33616 0.      0.33616] 

Iteration:  6
Error:  0.32767999999999997
Weight Vector: [0.368928 0.       0.368928] 

Iteration:  7
Error:  0.26214399999999993
Weight Vector: [0.3951424 0.        0.3951424] 

Iteration:  8
Error:  0.2097152
Weight Vector: [0.41611392 0.         0.41611392] 

Iteration:  9
Error:  0.16777215999999995
Weight Vector: [0.43289114 0.         0.43289114] 

Iteration:  10
Error:  0.13421772799999998
Weight Vector: [0.44631291 0.         0.44631291] 

Iteration:  11
Error:  0.10737418239999996
Weight Vector: [0.45705033 0.         0.45705033] 

Iteration:  12
Error:  0.08589934591999993
Weight Vector: [0.46564026 0.         0.46564026] 

Iteration: