### Importing Library

In [1]:
import numpy as np

### Max-Min Composition

In [2]:
def maxMin(X, y):
    z = []
    for x1 in X:
        for y1 in y.T:
            z.append(max(np.minimum(x1, y1)))
    
    return np.array(z).reshape((X.shape[0], y.shape[1]))

In [3]:
r1 =np.array([[0.6, 0.3], [0.2, 0.9]])
r2 =np.array([[1, 0.5, 0.3], [0.8, 0.4, 0.7]])

print("R1: ", r1)
print("R2: ", r2)

R1:  [[0.6 0.3]
 [0.2 0.9]]
R2:  [[1.  0.5 0.3]
 [0.8 0.4 0.7]]


In [4]:
print("Max-Min: \n" + str(maxMin(r1, r2)) + "\n")

Max-Min: 
[[0.6 0.5 0.3]
 [0.8 0.4 0.7]]

