# 2. Implementation of Fuzzy Relation (Max-Min Composition)

In [1]:
import numpy as np

def maxMin(X, y):
    z = []
    for x1 in X:
        for y1 in y.T:
            z.append(max(np.minimum(x1, y1)))
    
    return np.array(z).reshape((X.shape[0], y.shape[1]))

r1 =np.array([[0.6, 0.3], [0.2, 0.9]])
r2 =np.array([[1, 0.5, 0.3], [0.8, 0.4, 0.7]])

print("R1: ", r1)
print("R2: ", r2)
print("\nMax-Min: \n" + str(maxMin(r1, r2)) + "\n")

R1:  [[0.6 0.3]
 [0.2 0.9]]
R2:  [[1.  0.5 0.3]
 [0.8 0.4 0.7]]

Max-Min: 
[[0.6 0.5 0.3]
 [0.8 0.4 0.7]]



# 3. Implementation of Simple Neural Network

In [2]:
def threshold(x, t):
    if x >= t:
        return 1
    else:
        return 0

def mcCulloh_pitts(inputs, weights, t = 0):
    weighted_sum = inputs @ weights
    print(f'Weighted_sum: {weighted_sum}')
    output = threshold(weighted_sum, t)
    return output

inputs = np.array([1, 0, 1])
weights = np.array([1, 0, 1])
t = 1
output = mcCulloh_pitts(inputs, weights, t)
print("The Final Output is {}".format(output))

Weighted_sum: 2
The Final Output is 1


# 4. Implement Single Layer Perceptron

In [3]:
class Perceptron():
    def __init__(self, input_size, learning_rate):
        self.weights = np.zeros(input_size)
        self.learning_rate = learning_rate
        
    def predict(self, inputs):
        summation = np.dot(self.weights, inputs)
        activation = np.where(summation >= -0.1, 1, 0)
        return activation
    
    def train(self, inputs, labels, epochs):
        for _ in range(epochs):
            for i, x in enumerate(inputs):
                y = self.predict(x)
                error = labels[i] - y
                self.weights = self.learning_rate * error * x

In [4]:
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
labels = np.array([1,1,1,0])

p = Perceptron(2, 0.1)

p.train(inputs, labels, 10)

test_inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
for i in range(len(test_inputs)):
    print("Input: ", test_inputs[i], "Output: ", p.predict(test_inputs[i]))

Input:  [0 0] Output:  1
Input:  [0 1] Output:  1
Input:  [1 0] Output:  1
Input:  [1 1] Output:  0


# 5. Apply Hebbs and Delta Rule

In [5]:
import numpy as np

# Hebbs Rule
xl = np.array([1, 0, 1])
x2 = np.array([0, 1, 0])
w = np.zeros((3, 3))

# Apply Hebb 's rule to update the weight matrix
w += np.outer(xl, xl)
w += np.outer(x2, x2)

print("Weight matrix after applying Hebb's rule: ")
print(w)

Weight matrix after applying Hebb's rule: 
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [6]:
# Delta Rule
# Define the input vector and desired output
x = np.array([1, 0, 1])
d = 1

# Initialize the weight vector and leanring rate
w = np.zeros(3)
lr = 0.1

# Repeat the training process until convergence
for i in range(100):
    # Compute the output
    y = np.dot(w, x)
    
    # Compute the error between the network's and the desired output
    e = d - y
    
    # Update the weight vector using Delta Rule
    w += lr * e * x
    
    # Print the error and the weight vector
    print("Iteration: ", i + 1)
    print("Error: ", e)
    print("Weight Vector:", w, "\n")

Iteration:  1
Error:  1.0
Weight Vector: [0.1 0.  0.1] 

Iteration:  2
Error:  0.8
Weight Vector: [0.18 0.   0.18] 

Iteration:  3
Error:  0.6399999999999999
Weight Vector: [0.244 0.    0.244] 

Iteration:  4
Error:  0.512
Weight Vector: [0.2952 0.     0.2952] 

Iteration:  5
Error:  0.40959999999999996
Weight Vector: [0.33616 0.      0.33616] 

Iteration:  6
Error:  0.32767999999999997
Weight Vector: [0.368928 0.       0.368928] 

Iteration:  7
Error:  0.26214399999999993
Weight Vector: [0.3951424 0.        0.3951424] 

Iteration:  8
Error:  0.2097152
Weight Vector: [0.41611392 0.         0.41611392] 

Iteration:  9
Error:  0.16777215999999995
Weight Vector: [0.43289114 0.         0.43289114] 

Iteration:  10
Error:  0.13421772799999998
Weight Vector: [0.44631291 0.         0.44631291] 

Iteration:  11
Error:  0.10737418239999996
Weight Vector: [0.45705033 0.         0.45705033] 

Iteration:  12
Error:  0.08589934591999993
Weight Vector: [0.46564026 0.         0.46564026] 

Iteration:

# 6. Write a program for Error Back Propogation Algorithm(EBPA) Learning

In [7]:
class EBP:
    def __init__(self, learning_rate = 0.1, epochs = 50):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None
        
    def activation_func(self, summation):
        if summation >= 0:
            return 1
        else:
            return 0
        
    def fit(self, X, y):
        print(f'shape of X {X.shape}') # (rows, columns) -> X.shape[0] = no. of rows and X.shape[1] = no. of columns
        print(f'shape of y {y.shape}')
        
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        
        for _ in range(self.epochs):
            for i in range(X.shape[0]):
                summation = np.dot(X[i], self.weights) + self.bias
                y_pred = self.activation_func(summation)
                
                self.weights = self.weights + self.learning_rate * (y[i] - y_pred) * X[i]
                self.bias = self.bias + self.learning_rate * (y[i] - y_pred)
                
        print('Training complete')
        print(f'Weights are {self.weights}')
        print(f'Biases are {self.bias}')
        
    def predict(self, X):
        y_pred = []
        for i in range(X.shape[0]):
            y_prediction = self.activation_func(np.dot(self.weights, X[i]) + self.bias)
            y_pred.append(y_prediction)
            
        return np.array(y_pred)

In [8]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([1, 1, 1, 0])

In [9]:
p = EBP()
p.fit(X, y)

shape of X (4, 2)
shape of y (4,)
Training complete
Weights are [-0.2 -0.1]
Biases are 0.2


In [10]:
test_inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
y_pred = []
for i in range(test_inputs.shape[0]):
  print(f'Input : {test_inputs[i]} , Output : {p.predict(test_inputs)[i]}')

Input : [0 0] , Output : 1
Input : [0 1] , Output : 1
Input : [1 0] , Output : 1
Input : [1 1] , Output : 0


# 9. Design a fuzzy controller

In [11]:
!pip install -U scikit-fuzzy

In [12]:
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# Define input variables
water_level = ctrl.Antecedent(np.arange(0, 11, 1), 'water_level')
dirt_level = ctrl.Antecedent(np.arange(0, 11, 1), 'dirt_level')

# Define output variable
detergent_amount = ctrl.Consequent(np.arange(0, 11, 1), 'detergent_amount')

# Define membership functions for input variables
water_level['low'] = fuzz.trimf(water_level.universe, [0, 0, 5])
water_level['medium'] = fuzz.trimf(water_level.universe, [0, 5, 10])
water_level['high'] = fuzz.trimf(water_level.universe, [5, 10, 10])

dirt_level['low'] = fuzz.trimf(dirt_level.universe, [0, 0, 5])
dirt_level['medium'] = fuzz.trimf(dirt_level.universe, [0, 5, 10])
dirt_level['high'] = fuzz.trimf(dirt_level.universe, [5, 10, 10])

# Define membership functions for output variable
detergent_amount['low'] = fuzz.trimf(detergent_amount.universe, [0, 0, 5])
detergent_amount['medium'] = fuzz.trimf(detergent_amount.universe, [0, 5, 10])
detergent_amount['high'] = fuzz.trimf(detergent_amount.universe, [5, 10, 10])

# Define fuzzy rules
rule1 = ctrl.Rule(water_level['low'] & dirt_level['low'], detergent_amount['low'])
rule2 = ctrl.Rule(water_level['low'] & dirt_level['medium'], detergent_amount['low'])
rule3 = ctrl.Rule(water_level['low'] & dirt_level['high'], detergent_amount['medium'])
rule4 = ctrl.Rule(water_level['medium'] & dirt_level['low'], detergent_amount['low'])
rule5 = ctrl.Rule(water_level['medium'] & dirt_level['medium'], detergent_amount['medium'])
rule6 = ctrl.Rule(water_level['medium'] & dirt_level['high'], detergent_amount['high'])
rule7 = ctrl.Rule(water_level['high'] & dirt_level['low'], detergent_amount['medium'])
rule8 = ctrl.Rule(water_level['high'] & dirt_level['medium'], detergent_amount['high'])
rule9 = ctrl.Rule(water_level['high'] & dirt_level['high'], detergent_amount['high'])

# Define control system
washing_machine_ctrl = ctrl.ControlSystem(
    [rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9])

# Define simulation
washing_machine_sim = ctrl.ControlSystemSimulation(washing_machine_ctrl)

# Set input values
washing_machine_sim.input['water_level'] = 3
washing_machine_sim.input['dirt_level'] = 7

# Run simulation
washing_machine_sim.compute()

# Print output value
print(washing_machine_sim.output['detergent_amount'])

4.999999999999998


# Ignore

### 1. Study of Fuzzy Operations

In [13]:
A = {10,11,12,13}
B = {11,12,13,14,15}
print("A: ", A)
print("B: ", B)

# UNION
Union = A.union(B)
print("Union: ", Union) #{10, 11, 12, 13, 14, 15}

# INTERSECTION
Intersection = A.intersection(B)
print("Intersection: ", Intersection) #{11, 12, 13}

# COMPLEMENT
Complement = B - A
print("Complement: ", Complement) #{14, 15}

# ALGEBRIC SUM
A = {0.2/1 + 0.3/2 + 0.4/3 + 0.5/4}
B = {0.1/1 + 0.2/2 + 0.2/3 + 0/4}
# µ(A+B) = µ(A) + µ(B) - (µ(A) * µ(B))
Algebricsum = {0.3/1 + 0.5/2 + 0.6/3 + 0.5/4} - {0.02/1 + 0.06/2 + 0.08/3 + 0/4}
Algebricsum = {0.28/1 + 0.44/2 + 0.52/3 + 0.5/4}
print("Algebricsum: ", Algebricsum)

# ALGEBRIC PRODUCT
A = {0.2/1 + 0.3/2 + 0.4/3 + 0.5/4}
B = {0.1/1 + 0.2/2 + 0.2/3 + 0/4}
# µ(A*B) = (µ(A) * µ(B))
AlgebricProduct = {0.02/1 + 0.06/2 + 0.08/3 + 0/4}
print("AlgebricProduct: ", AlgebricProduct)

A:  {10, 11, 12, 13}
B:  {11, 12, 13, 14, 15}
Union:  {10, 11, 12, 13, 14, 15}
Intersection:  {11, 12, 13}
Complement:  {14, 15}
Algebricsum:  {0.7983333333333333}
AlgebricProduct:  {0.07666666666666667}


### 7. Implementation of Simple Genetic Algorithm

In [14]:
import numpy as np

# Define parameters
pop_size = 10
num_genes = 5
mutation_rate = 0.1
crossover_rate = 0.5
num_generations = 100

# Define fitness function
def fitness(individual):
    return sum(individual)

# Initialize population
population = np.random.randint(2, size=(pop_size, num_genes))

# Evolution loop
for generation in range(num_generations):
    # Calculate fitness scores
    fitness_scores = [fitness(individual) for individual in population]
    # Select parents for crossover
    parent_indices = np.random.choice(pop_size, size=2, replace=False, p=np.array(fitness_scores)/sum(fitness_scores))
    parents = population[parent_indices]
    # Perform crossover
    if np.random.random() < crossover_rate:
        crossover_point = np.random.randint(num_genes)
        offspring = np.concatenate([parents[0][:crossover_point], parents[1][crossover_point:]])
    else:
        offspring = parents[0]
    # Perform mutation
    for i in range(num_genes):
        if np.random.random() < mutation_rate:
            offspring[i] = 1 - offspring[i]
    # Replace least fit individual in population with offspring
    least_fit_index = np.argmin(fitness_scores)
    population[least_fit_index] = offspring

# Print final population and fitness scores
print("Final population:")
print(population)
print("Fitness scores:")
print([fitness(individual) for individual in population])


Final population:
[[0 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Fitness scores:
[3, 5, 5, 5, 5, 5, 5, 5, 5, 5]


### 8. Implementation of Unsupervised Learning Algorithm

In [15]:
import numpy as np
from sklearn.cluster import KMeans

# Generate some random data
data = np.random.rand(100, 2)

# Define the number of clusters
k = 3

# Initialize the KMeans object
kmeans = KMeans(n_clusters=k)

# Fit the data to the KMeans object
kmeans.fit(data)

# Get the cluster labels for each data point
labels = kmeans.labels_

# Get the cluster centers
centers = kmeans.cluster_centers_

# Print the cluster labels and centers
print("Cluster labels:\n", labels)
print("Cluster centers:\n", centers)


AttributeError: 'NoneType' object has no attribute 'split'