1. Study of Fuzzy Operations

In [4]:
A = {10,11,12,13}
B = {11,12,13,14,15}

# UNION
Union = A.union(B)
print(Union) #{10, 11, 12, 13, 14, 15}

# INTERSECTION
Intersection = A.intersection(B)
print(Intersection) #{11, 12, 13}

# COMPLEMENT
Complement = B - A
print(Complement) #{14, 15}

# ALGEBRIC SUM
A = {0.2/1 + 0.3/2 + 0.4/3 + 0.5/4}
B = {0.1/1 + 0.2/2 + 0.2/3 + 0/4}
µ(A+B) = µ(A) + µ(B) - (µ(A) * µ(B))
Algebricsum = {0.3/1 + 0.5/2 + 0.6/3 + 0.5/4} - {0.02/1 + 0.06/2 + 0.08/3 + 0/4}
Algebricsum = {0.28/1 + 0.44/2 + 0.52/3 + 0.5/4}

# ALGEBRIC PRODUCT
A = {0.2/1 + 0.3/2 + 0.4/3 + 0.5/4}
B = {0.1/1 + 0.2/2 + 0.2/3 + 0/4}
µ(A*B) = (µ(A) * µ(B))
AlgebricProduct = {0.02/1 + 0.06/2 + 0.08/3 + 0/4}



{10, 11, 12, 13, 14, 15}
{11, 12, 13}
{14, 15}


2.Implementation of Fuzzy Relation (Max-Min Composition)

In [9]:
import numpy as np
A = [
    [0.5, 0.2, 0.3],
    [0.1, 0.7, 0.6],
    [0.3, 0.5, 0.8]
    ]

B = [
    [0.6, 0.3, 0.1],
    [0.2, 0.5, 0.8],
    [0.8, 0.1, 0.5]
    ]

A = np.array(A)
B = np.array(B)

T = np.zeros((len(A),len(B)))

for i in range(len(A)):
    for j in range(len(B)):
        T[i,j] = np.max(np.minimum(A[i,:], B[:,j]))

print("Max-Min Composition:\n",T)


Max-Min Composition:
 [[0.5 0.3 0.3]
 [0.6 0.5 0.7]
 [0.8 0.5 0.5]]


3.Implementation of Simple Neural Network

In [10]:
def threshold(x):
    if x >= 0:
        return 1
    else:
        return 0

def mcCulloh_pitts(inputs,weights):
    weighted_sum = sum([inputs[i]*weights[i] for i in range(len(inputs))])
    output = threshold(weighted_sum)
    return output

inputs = [1,0,1]
weights = [0.5,-0.5,0.5]
output = mcCulloh_pitts(inputs,weights)
print("The Final Output is {}".format(output))

The Final Output is 1


4.Implement Single Layer Perceptron

In [15]:
from sklearn.linear_model import Perceptron
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])
clf = Perceptron()
clf.fit(X, y)
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predictions = clf.predict(test_data)
print(predictions)

# Scratch
import numpy as np

# Input data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Output data
Y = np.array([[0], [0], [0], [1]])

# Step function
def step_function(x):
    return np.where(x > 0, 1, 0)

# Initialize weights and bias
W = np.random.rand(2, 1)
b = np.random.rand(1)

# Learning rate
lr = 0.1

# Training the model
for i in range(10000):
    # Forward propagation
    Z = np.dot(X, W) + b
    A = step_function(Z)

    # Backward propagation
    error = Y - A
    dW = lr * np.dot(X.T, error)
    db = lr * np.sum(error)

    # Update weights and bias
    W += dW
    b += db

# Testing the model
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for x in test_data:
    result = step_function(np.dot(x, W) + b)
    print(f"{x[0]} AND {x[1]} = {result}")


[0 0 0 1]
0 AND 0 = [0]
0 AND 1 = [0]
1 AND 0 = [0]
1 AND 1 = [1]


5.Apply Hebbs and Delta Rule

In [17]:
# Hebbs Rule
import numpy as np
X = np.array([[1,0,0],[0,1,0],[0,0,1],[-1,0,0],[0,-1,0],[0,0,-1]])
W = np.random.rand(3,3)
lr = 0.1
for i in range(X.shape[0]):
    x = X[i].reshape(-1,1)
    W += lr * np.dot(x,x.T)
print(W)


[[0.77955031 0.22553648 0.98385229]
 [0.26299372 0.32367958 0.69123334]
 [0.84606871 0.74841357 0.25119327]]


In [19]:
# Delta Rule
X = np.array([[1,0,0],[0,1,0],[0,0,1],[-1,0,0],[0,-1,0],[0,0,-1]])
Y = np.array([[1],[1],[1],[-1],[-1],[-1],])
W = np.random.rand(3,1)
lr = 0.1

for i in range(X.shape[0]):
    x = X[i].reshape(-1,1)
    error = Y[i] - np.dot(W.T,x)
    W += lr * error * x
print(W)


[[0.47757617]
 [0.94216636]
 [0.5126008 ]]


6.Write a program for Error Back Propogation Algorithm(EBPA) Learning

In [20]:
import numpy as np

# Define sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define derivative of sigmoid activation function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define training data
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# Define hyperparameters
learning_rate = 0.1
num_epochs = 10000
num_hidden_units = 4

# Initialize weights
input_dim = X.shape[1]
output_dim = y.shape[1]

W1 = np.random.randn(input_dim, num_hidden_units)
b1 = np.zeros((1, num_hidden_units))

W2 = np.random.randn(num_hidden_units, output_dim)
b2 = np.zeros((1, output_dim))

# Train the network using backpropagation
for epoch in range(num_epochs):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    
    # Compute error
    error = y - a2
    
    # Backward pass
    delta2 = error * sigmoid_derivative(a2)
    dW2 = np.dot(a1.T, delta2)
    db2 = np.sum(delta2, axis=0, keepdims=True)
    
    delta1 = np.dot(delta2, W2.T) * sigmoid_derivative(a1)
    dW1 = np.dot(X.T, delta1)
    db1 = np.sum(delta1, axis=0, keepdims=True)
    
    # Update weights
    W2 += learning_rate * dW2
    b2 += learning_rate * db2
    W1 += learning_rate * dW1
    b1 += learning_rate * db1
    
# Predict output for new input
new_input = np.array([[1, 0, 0]])
z1 = np.dot(new_input, W1) + b1
a1 = sigmoid(z1)

z2 = np.dot(a1, W2) + b2
a2 = sigmoid(z2)

print(a2)


[[0.72128524]]


7. Implementation of Simple Genetic Algorithm

In [21]:
import numpy as np

# Define parameters
pop_size = 10
num_genes = 5
mutation_rate = 0.1
crossover_rate = 0.5
num_generations = 100

# Define fitness function
def fitness(individual):
    return sum(individual)

# Initialize population
population = np.random.randint(2, size=(pop_size, num_genes))

# Evolution loop
for generation in range(num_generations):
    # Calculate fitness scores
    fitness_scores = [fitness(individual) for individual in population]
    # Select parents for crossover
    parent_indices = np.random.choice(pop_size, size=2, replace=False, p=np.array(fitness_scores)/sum(fitness_scores))
    parents = population[parent_indices]
    # Perform crossover
    if np.random.random() < crossover_rate:
        crossover_point = np.random.randint(num_genes)
        offspring = np.concatenate([parents[0][:crossover_point], parents[1][crossover_point:]])
    else:
        offspring = parents[0]
    # Perform mutation
    for i in range(num_genes):
        if np.random.random() < mutation_rate:
            offspring[i] = 1 - offspring[i]
    # Replace least fit individual in population with offspring
    least_fit_index = np.argmin(fitness_scores)
    population[least_fit_index] = offspring

# Print final population and fitness scores
print("Final population:")
print(population)
print("Fitness scores:")
print([fitness(individual) for individual in population])


Final population:
[[1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Fitness scores:
[4, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [ ]:
8.Implementation of Unsupervised Learning Algorithm

In [23]:
import numpy as np
from sklearn.cluster import KMeans

# Generate some random data
data = np.random.rand(100, 2)

# Define the number of clusters
k = 3

# Initialize the KMeans object
kmeans = KMeans(n_clusters=k)

# Fit the data to the KMeans object
kmeans.fit(data)

# Get the cluster labels for each data point
labels = kmeans.labels_

# Get the cluster centers
centers = kmeans.cluster_centers_

# Print the cluster labels and centers
print("Cluster labels:\n", labels)
print("Cluster centers:\n", centers)


Cluster labels:
 [1 0 1 1 2 1 0 1 1 1 2 1 0 2 1 2 0 1 1 2 0 0 1 1 0 1 1 2 2 0 1 1 1 1 0 2 0
 2 1 1 2 1 2 0 0 1 0 2 0 1 1 2 1 2 2 2 0 0 0 2 2 1 0 1 2 1 1 1 1 1 0 0 2 0
 0 2 0 0 1 2 0 0 0 0 1 2 2 2 0 1 1 0 1 1 0 1 2 2 0 1]
Cluster centers:
 [[0.2240113  0.24001213]
 [0.44043541 0.7912953 ]
 [0.78689446 0.33682595]]


9.Design a fuzzy controller

In [32]:
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# Define input variables
water_level = ctrl.Antecedent(np.arange(0, 11, 1), 'water_level')
dirt_level = ctrl.Antecedent(np.arange(0, 11, 1), 'dirt_level')

# Define output variable
detergent_amount = ctrl.Consequent(np.arange(0, 11, 1), 'detergent_amount')

# Define membership functions for input variables
water_level['low'] = fuzz.trimf(water_level.universe, [0, 0, 5])
water_level['medium'] = fuzz.trimf(water_level.universe, [0, 5, 10])
water_level['high'] = fuzz.trimf(water_level.universe, [5, 10, 10])

dirt_level['low'] = fuzz.trimf(dirt_level.universe, [0, 0, 5])
dirt_level['medium'] = fuzz.trimf(dirt_level.universe, [0, 5, 10])
dirt_level['high'] = fuzz.trimf(dirt_level.universe, [5, 10, 10])

# Define membership functions for output variable
detergent_amount['low'] = fuzz.trimf(detergent_amount.universe, [0, 0, 5])
detergent_amount['medium'] = fuzz.trimf(detergent_amount.universe, [0, 5, 10])
detergent_amount['high'] = fuzz.trimf(detergent_amount.universe, [5, 10, 10])

# Define fuzzy rules
rule1 = ctrl.Rule(water_level['low'] & dirt_level['low'], detergent_amount['low'])
rule2 = ctrl.Rule(water_level['low'] & dirt_level['medium'], detergent_amount['low'])
rule3 = ctrl.Rule(water_level['low'] & dirt_level['high'], detergent_amount['medium'])
rule4 = ctrl.Rule(water_level['medium'] & dirt_level['low'], detergent_amount['low'])
rule5 = ctrl.Rule(water_level['medium'] & dirt_level['medium'], detergent_amount['medium'])
rule6 = ctrl.Rule(water_level['medium'] & dirt_level['high'], detergent_amount['high'])
rule7 = ctrl.Rule(water_level['high'] & dirt_level['low'], detergent_amount['medium'])
rule8 = ctrl.Rule(water_level['high'] & dirt_level['medium'], detergent_amount['high'])
rule9 = ctrl.Rule(water_level['high'] & dirt_level['high'], detergent_amount['high'])

# Define control system
washing_machine_ctrl = ctrl.ControlSystem(
    [rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9])

# Define simulation
washing_machine_sim = ctrl.ControlSystemSimulation(washing_machine_ctrl)

# Set input values
washing_machine_sim.input['water_level'] = 3
washing_machine_sim.input['dirt_level'] = 7

# Run simulation
washing_machine_sim.compute()

# Print output value
print(washing_machine_sim.output['detergent_amount'])


4.999999999999998


In [27]:
pip install numpy scipy

Note: you may need to restart the kernel to use updated packages.


In [30]:
pip install -U scikit-fuzzy


  Created wheel for scikit-fuzzy: filename=scikit_fuzzy-0.4.2-py3-none-any.whl size=894089 sha256=9374a7294ed976eecab0710280a197ae633bf39fdde77ba8d718d9709174f780
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\32\2c\a1\a90a7d7dd8448ec029f298a61f3490275e99b17aa348be675c
Successfully built scikit-fuzzy
